export const baseTokens = {
    colors: {
        primary: 'rgba(12, 68, 59, 1)',
        primaryTint: 'rgba(12, 68, 59, 0.12)',
        primaryBorder: 'rgba(12, 68, 59, 0.4)',
        primaryBorderStrong: 'rgba(12, 68, 59, 0.6)',
        neutral900: '#2c2c2c',
        neutral800: '#444444',
        neutral750: '#333333',
        neutral700: '#666666',
        neutral600: '#999999',
        surface: 'rgba(255,255,255,0.95)',
        surfaceGlass: 'rgba(255,255,255,0.2)',
        surfaceGlassStrong: 'rgba(255,255,255,0.3)',
        surfaceSolid: '#ffffff',
        textOnSurface: '#000000',
        textOnPrimary: '#ffffff',
        loadingRing: '#ffffff',
    },
    typography: {
        display: "'GungnipClassic', serif",
        heading: "'GungnipClassic', serif",
        body: "'Noto Serif KR', serif",
        accent: "'GungnipClassic', serif",
        weightLight: '300',
        weightRegular: '400',
        weightMedium: '500',
        sizeHero: 'clamp(36px, 8vw, 72px)',
        sizeSubtitle: 'clamp(30px, 3vw, 42px)',
        sizeBody: 'clamp(12px, 2vw, 18px)',
        sizeBodySmall: 'clamp(10px, 1.8vw, 16px)',
        sizeButton: 'clamp(16px, 2vw, 18px)',
        sizeLoading: 'clamp(16px, 2.5vw, 20px)',
        sizeResultYear: 'clamp(14px, 2vw, 18px)',
        sizeResultTitle: 'clamp(20px, 3vw, 28px)',
        sizeVerse: 'clamp(16px, 2.5vw, 20px)',
        sizeVerseReference: 'clamp(14px, 2vw, 16px)',
        sizeResultLogo: 'clamp(12px, 1.5vw, 14px)',
        sizeResultLogoSaving: '22px',
        sizeResultYearSaving: '32px',
        sizeResultTitleSaving: '44px',
        sizeVerseSaving: '34px',
        sizeVerseReferenceSaving: '26px',
        lineHeightTight: '1.2',
        lineHeightBody: '1.6',
        lineHeightHeading: '1.4',
        lineHeightVerse: 'clamp(1.6, 0.2vw + 1.5, 2)',
        lineHeightVerseSaving: '1.8',
        letterSpacingHero: '2px',
        letterSpacingSubtitle: 'clamp(2px, 1vw, 8px)',
        letterSpacingBody: '1px',
        letterSpacingResultYear: '2px',
        letterSpacingResultTitle: 'clamp(2px, 0.5vw, 4px)',
        letterSpacingResultLogo: '2px',
        letterSpacingResultLogoSaving: '3px',
        letterSpacingSavingTitle: '6px',
        letterSpacingSavingReference: '1px',
        letterSpacingLoading: '2px',
    },
    spacing: {
        heroPadding: '40px 20px',
        heroPaddingTablet: '30px 15px',
        heroPaddingMobile: '20px 15px',
        heroTitleMargin: '20px',
        heroSubtitleMargin: '30px',
        verseMarginTop: '14px',
        startButtonMargin: '60px',
        startButtonMarginTablet: '40px',
        startButtonMarginMobile: '30px',
        startButtonPadding: '18px 50px',
        startButtonPaddingTablet: '16px 40px',
        startButtonPaddingMobile: '14px 30px',
        loadingIconMargin: '40px',
        loadingIconMarginMobile: '30px',
        layoutPadding: '40px 20px',
        layoutPaddingTablet: '30px 15px',
        layoutPaddingMobile: '20px 10px',
        cardPadding: 'clamp(30px, 5vw, 60px) clamp(25px, 4vw, 50px)',
        cardPaddingTablet: '40px 35px',
        cardPaddingMobile: '35px 25px',
        cardPaddingSmall: '30px 20px',
        cardPaddingTiny: '25px 15px',
        cardMarginBottom: '40px',
        headerMarginBottom: 'clamp(20px, 4vw, 40px)',
        verseMargin: 'clamp(20px, 4vw, 40px)',
        versePaddingInline: '0 10px',
        versePaddingSaving: '0 20px',
        verseMarginBottomSaving: '30px',
        verseWrapperGap: '15px',
        logoMarginTop: 'clamp(20px, 4vw, 40px)',
        buttonGap: 'clamp(12px, 2vw, 20px)',
        buttonGapMobile: 'clamp(10px, 2vw, 15px)',
        buttonRowGapMobile: 'clamp(10px, 2vw, 15px)',
        buttonContainerGap: 'clamp(12px, 2vw, 20px)',
        buttonContainerGapMobile: 'clamp(10px, 2vw, 15px)',
        savingPaddingTop: '220px',
        savingCardPadding: '100px 70px',
        savingCardMarginBottom: '200px',
        savingLogoBottom: '40px',
        savingLogoMarginBottom: '40px',
        resultYearMarginBottom: '10px',
        resultYearMarginBottomSaving: '20px',
    },
    size: {
        loadingIcon: 'clamp(80px, 15vw, 120px)',
        loadingRingWidth: '3px',
        cardMaxWidth: '600px',
        contentWidth: '90%',
        buttonContainerMaxWidth: '600px',
        buttonContainerWidth: '90%',
        borderWidth: '2px',
        hoverLift: '-2px',
        savingCardWidth: '720px',
        savingCardMinHeight: '1100px',
        savingContainerWidth: '1080px',
        savingContainerHeight: '1920px',
        logoWidth: '180px',
    },
    radius: {
        pill: '50px',
        card: '30px',
        cardLarge: '40px',
        cardMedium: '20px',
        cardSmall: '15px',
    },
    shadow: {
        textGlow: '0 0 30px rgba(255,255,255,0.5)',
        card: '0 20px 60px rgba(0,0,0,0.2)',
        cardStrong: '0 30px 80px rgba(0,0,0,0.25)',
        button: '0 10px 30px rgba(12, 68, 59, 0.18)',
        glassCardBlur: '20px',
        glassButtonBlur: '10px',
        logoSavingOpacity: '0.5',
    },
    motion: {
        transitionFast: 'all 0.3s ease',
        spinDuration: '1s',
        spinTiming: 'linear',
    },
    assets: {
        background: '/assets/images/back.jpg',
        logo: '/assets/logos/HaneulLogo.png',
        favicon: '/assets/logos/HaneulLogo.png',
    },
};

export function createTheme(overrides = {}) {
    return {
        name: overrides.name || 'default',
        colors: { ...baseTokens.colors, ...(overrides.colors || {}) },
        typography: { ...baseTokens.typography, ...(overrides.typography || {}) },
        spacing: { ...baseTokens.spacing, ...(overrides.spacing || {}) },
        size: { ...baseTokens.size, ...(overrides.size || {}) },
        radius: { ...baseTokens.radius, ...(overrides.radius || {}) },
        shadow: { ...baseTokens.shadow, ...(overrides.shadow || {}) },
        motion: { ...baseTokens.motion, ...(overrides.motion || {}) },
        assets: { ...baseTokens.assets, ...(overrides.assets || {}) },
    };
}
